###
http://localhost:3000/api/tags/test

### 필수 파라미터 null
http://localhost:3000/api/tags/all?projectId=

### 필수 파라미터 없을 때
http://localhost:3000/api/tags/all?resourceId=A001,A002,A003

###
http://localhost:3000/api/tags/all?projectId=pro_111,pro_222&resourceId=A001,AAA001&tags=NAME:홍길동,NAME:소주

